### ISSUE TITLE
HTTP_RESPONSE_STATUS not supported in Flash Player

### ISSUE THREAD

**Issue by ddennis** [pmcmonagle/http-digest-as3#1]
From the description it seems you library should also work in the Flash player(browser).
This is not the case since HTTP_RESPONSE_STATUS is only available in Air. 
or am i misunderstanding something, otherwise nice work.

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/HTTPStatusEvent.html#HTTP_RESPONSE_STATUS

**Comment by pmcmonagle** [comment]
It looks like you're right. My original use case was for silent authentication (ie. no password prompt is sent to users) between a RESTful API server and AIR for Android/iOS mobile apps. It's likely that I made a false assumption about it working in the browser as well.

It may work in the browser using HTTP_STATUS in place of HTTP_RESPONSE_STATUS, but I don't have Flash installed anymore so it's not something I'm eager to test. I think the only difference is in timing; HTTP_RESPONSE_STATUS is guaranteed to fire before any response data comes through.

For now, I'll just change the description.
Thanks for your input!
